language: php

php: 
  - 5.5
  - 5.4
  - hhvm

notifications:
  slack: nukacode:HyFrc2QLi5PC5fPxadm07O5v
  webhooks:
      urls:
        - https://webhooks.gitter.im/e/213257627c4e40ffc03c
      on_success: always  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: false     # default: false

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - composer install

script:
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload  --format=php-clover coverage.clover